### ISSUE TITLE
doesn't work in the alfred3

### ISSUE THREAD

**Issue by yhan219** [ilstar/Shorten-URL#1]
Hello,this is a good project, why not update it?

**Comment by ilstar** [comment]
hey @yhan219 , thanks for opening the issue, the reason I didn't update it because the workflow wasn't  really being used by myself in last a few years, and some of the short url service were already dead, but I just made a simple update so it can work with Alfred3 now, you can download it from here https://github.com/ilstar/Shorten-URL/releases

**Comment by yhan219** [comment]
I don't know if the method I used was incorrect, but it's still not working. I used it, and I got nothing.

**Comment by ilstar** [comment]
@yhan219 Can you provide the steps that can reproduce the issue? some screenshots would be great!

**Comment by yhan219** [comment]
Sorry, I tried gif, but the file is too big. I typed `short https://www.ggogle.com` in alfred, then selected `goo.glm` and knocked `enter`, but there was nothing in the pasteboard.

**Comment by yhan219** [comment]
just like this:
https://github.com/yhan219/my-images/blob/master/2019-05-17%2018.07.22.gif

**Comment by ilstar** [comment]
Google has stopped the service of goo.gl, bit.ly seems still working.
